music/album/urls.py
from django.urls import path
from . import views
# from .views import  AlbumListView,AlbumDetailView,AlbumCreatView,AlbumDeleteView,AlbumUpdateView,AlbumSinger,SongDetailView




app_name = 'music'
urlpatterns = [
    path('album/',views.AlbumListView.as_view(), name='album_list' ),
    path('album/<int:pk>/', views.AlbumDetailView.as_view(), name='detail_view'),
    path('album/create/',views.AlbumCreatView.as_view(),name='create_view'),
    path('album/delete/<int:pk>/',views.AlbumDeleteView.as_view(),name='delete_view' ),
    path('album/update/<int:pk>/',views.AlbumUpdateView.as_view(),name='update_view'),
    path('album/multi/',views.AlbumSinger.as_view(),name='album_singer_create'),
    path('album/multi/<int:pk>/',views.AlbumSinger.as_view(),name='album_singer'),

    path('album/song/<int:pk>/',views.SongDetailView.as_view(), name='song_detail'),
    path('album/song/create/<int:song_id>/',views.SongVoteCreateView.as_view(), name='song_vote_create'),
    path('album/song/update/<int:song_id>/<int:pk>/', views.SongUpdateView.as_view(), name='song_vote_update')
    
]

music/music/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from user import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)

urlpatterns = [

    # path('', include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',include('album.urls')),
    # path('api/v1/', include('user.api_urls')),
    path('user/',include('user.urls')),
    path('accounts/',include('allauth.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/user/urls.py
from django.contrib import admin
from django.urls import path,include
# from .views import  RegisterView,
from django.contrib.auth import views as auth_view
from user import views as user_views
from django.conf import settings
from django.conf.urls.static import static




app_name = 'user'
urlpatterns = [
   
    
    # path('login/', auth_view.LoginView.as_view(),name='login'),
    path('login/', user_views.LoginFormView.as_view(),name='login'), 
    path('logout/',auth_view.LogoutView.as_view(),name='logout'),

    path('account/signup/', user_views.signup,name='sinup'),
    path('account/ajax/validate_username/', user_views.validate_username, name='validate_username'),
    path('account/account_activation_sent/', user_views.account_activation_sent, name='account_activation_sent'),
    path('account/activate/<uidb64>/<token>/', user_views.activate, name='activate'),
    path('account/signup_done/', user_views.signup_done, name='signup_done'),

    path('password_reset/',auth_view.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/',auth_view.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_view.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done',auth_view.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('profile/<int:pk>/',user_views.ProfileEditView.as_view(), name='edit_profile'),
    path('add_profile/<int:pk>/',user_views.ProfileAddView.as_view(), name='add_profile'),
    path('detail_profile/<int:pk>/',user_views.ProfileDetailView.as_view(), name='detail_profile'),

]







'''
need to install crispy form for better look using pip3 install django-crispy-forms,
and add the app in installed app like bellow

INSTALLED_APPS = [
    ...

    'crispy_forms',
]

and add the tag in settings.py as bellow

CRISPY_TEMPLATE_PACK = 'bootstrap4'

refer /home/sanjay/Hacker make/CRUD mixins/Bootstrap 4 Forms With Django for more info.
'''
    
    

music/album/models.py
from django.db import models
from uuid import uuid4

from django.contrib.auth import get_user_model
from django.core.exceptions import ObjectDoesNotExist

User = get_user_model()


class Singer(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)


    def __str__(self):
        return '{} {}'.format(self.first_name,self.last_name )  


class Album(models.Model):
    title = models.CharField(max_length=50)
    discription = models.TextField()
    album_creator = models.ForeignKey(Singer, related_name='sung_by', blank=True,null=True, on_delete=models.DO_NOTHING)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
 


    def __str__(self):
        return self.title

    @property
    def songs(self):
        return self.album_name.all()

    @property
    def vote(self):
        return self.albumvote_set.all()

class Song(models.Model):
    song_title = models.CharField(max_length=25)
    album = models.ForeignKey(Album, related_name='album_name', on_delete=models.CASCADE, blank=True)
    singer = models.ManyToManyField(Singer, blank=True)
    language = models.CharField(max_length=25)

    def __str__(self):
        return self.song_title

    
class VoteManager(models.Manager):

    def get_vote_or_unsaved_blank_vote(self,song,user):
        try:
            return Vote.objects.get(song=song,user=user)

        except ObjectDoesNotExist:
            return Vote(song=song,user=user)

class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICE = ((UP, "👍️"),(DOWN, "👎️"),)
    
    
    like = models.SmallIntegerField(null=True, blank=True, choices=VALUE_CHOICE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True)

    objects = VoteManager()

    class Meta:
        unique_together = ('user', 'song') #this represent user can vote at once for a song He can not vote song again and again

    def __str__(self):
        return '{}-{}-({})'.format(self.song, self.user,self.like)





class AlbumVoteManager(models.Manager):

    def get_vote_or_unsaved_blank_vote(self,album,user):
        try:
            return Vote.objects.get(album=album,user=user)

        except ObjectDoesNotExist:
            return Vote(album=album,user=user)


class AlbumVote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICE = ((UP, "👍️"),(DOWN, "👎️"),)
    
    
    like = models.SmallIntegerField(null=True, blank=True, choices=VALUE_CHOICE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    objects = AlbumVoteManager()

    class Meta:
        unique_together = ('user', 'album') #this represent user can vote at once for a song He can not vote song again and again

    def __str__(self):
        return '{}-{}-({})'.format(self.album, self.user,self.like)




class AlbumCommentManager(models.Manager):

    def get_vote_or_unsaved_blank_vote(self,album,user):
        try:
            return Vote.objects.get(album=album,user=user)

        except ObjectDoesNotExist:
            return Vote(album=album,user=user)


class AlbumComment(models.Model):
    comment = models.CharField(max_length=50)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    commented_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    objects = AlbumCommentManager()

    class Meta:
        unique_together = ('user', 'album') #this represent user can vote at once for a song He can not vote song again and again

    def __str__(self):
        return '{}-{}-({})'.format(self.album, self.user,self.commented_on)

music/album/views.py
from django.shortcuts import render,reverse,get_object_or_404,redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy

from django.views.decorators.cache import cache_page


from django.contrib.auth import authenticate,PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin


from django.http import HttpResponseRedirect
from django.views.generic import ListView,DetailView,CreateView,DeleteView,UpdateView,FormView,View

from .models import Album,Singer,Song,Vote,AlbumVote
from .form import AlbumForm,SingerForm,SongForm,SongVoteForm,AlbumVoteForm,AlbumCommentForm




class SongDetailView(DetailView):
    model = Song
    template_name = 'song/song_detail.html'

    def get_context_data(self,**kwargs):
        ctx = super().get_context_data(**kwargs)


        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(song=self.object, user = self.request.user)
            if vote.id:
                vote_url = reverse('music:song_vote_update', kwargs={'song_id':vote.song.id,'pk':vote.id}) #'pk':vote.id
            else:
                vote_url = reverse('music:song_vote_create', kwargs={'song_id':self.object.id}) #

            vote_form = SongVoteForm(instance=vote)
            ctx['vote_form'] = vote_form
            ctx['vote_url'] = vote_url
        return ctx



class SongVoteCreateView(LoginRequiredMixin, CreateView):
    form_class = SongVoteForm
    model = Vote
    # fields = ['like']
    

    def get_success_url(self,**kwargs):
        song_id = self.kwargs.get('song_id')
        return reverse('music:song_detail', kwargs={'pk':song_id})
 
    def form_valid(self, form):
        like = form.cleaned_data.get('like')
        user = self.request.user
        song_obj = Song.objects.get(pk=self.kwargs['song_id'])
        vote_obj, created = Vote.objects.get_or_create(song = song_obj, user = user, like=like) 
        form.instance = vote_obj
        return super().form_valid(form)


class SongUpdateView(LoginRequiredMixin, UpdateView):
    form_class = SongVoteForm
    model = Vote

    def get_success_url(self):
        song_id = self.kwargs.get('song_id')
        return reverse('music:song_detail', kwargs={'pk':song_id})


class AlbumSinger(View):
    singer_class = SingerForm
    album_class = AlbumForm
    song_class = SongForm
    template_name = 'album/multi_form_edit.html'
    

    def get(self,request,pk=None):
        if pk:
            
            album_obj = get_object_or_404(Album, pk=pk)
            singer_obj = album_obj.album_creator
            songs = album_obj.album_name.all()

            singer_form = SingerForm(instance=singer_obj)
            album_form = AlbumForm(instance=album_obj)
            song_form = [SongForm(prefix=str(song.id),instance=song)for song in songs]

            context = {
                'singer_form':singer_form,
                'album_form':album_form,
                'song_form':song_form,
            }
            return render(request, self.template_name, context)
        else:
            singer_form = self.singer_class(None)
            album_form = self.album_class(None)
            song_form = [SongForm(instance=Song())]

            context = {
                'singer_form':singer_form,
                'album_form':album_form,
                'song_form':song_form
            }
            return render(request, self.template_name, context)

    def post(self,request,pk=None):
        context = {}
        
        album_obj,created = Album.objects.get_or_create(pk=pk)
        singer_obj = album_obj.album_creator
        songs = album_obj.album_name.all()

        singer_form = SingerForm(request.POST, instance=singer_obj)
        album_form = AlbumForm(request.POST,instance=album_obj)
        song_form = [SongForm(request.POST,instance=song)for song in songs]

        if singer_form.is_valid() and album_form.is_valid() and all([sf.is_valid for sf in song_form]):
            singer_instance = singer_form.save()
            new_album = album_form.save(commit=False)
            new_album.album_creator = singer_instance
            new_album.save()

            for sf in song_form:
                new_song = sf.save(commit=False)
                new_song.album = new_album
                new_song.singer.add(singer_instance) 
                new_song.save()
            return HttpResponseRedirect('/album/')
        context = {
            'singer_form' : singer_form,
            'album_form' : album_form
        }
        return render(request, 'album/multi_form.html', context) 


@method_decorator(cache_page(200), name='dispatch')
class AlbumListView(ListView):
    model = Album
    paginate_by = 5
    
    # print('not cached')
    def get_context_data(self,**kwargs):
        ctx = super().get_context_data(**kwargs)

        # if self.request.user.is_authenticated:
        #     vote = AlbumVote.objects.get_vote_or_unsaved_blank_vote(album=self.object_list.object, user = self.request.user)
        #     if vote.id:
        #         vote_url = reverse('music:album_vote_update', kwargs={'album_id':vote.album.id,'pk':vote.id})
        #     else:
        #         vote_url = reverse('music:album_vote_create', kwargs={'album_id':self.object_list.object.id})


        #     vote_form = AlbumVoteForm(instance=vote)
        #     ctx['vote_form'] = vote_form
        #     ctx['vote_url'] = 
        print('Not chached') #This is used to check cashing
        return ctx

    

class AlbumVoteCreateView(CreateView):
    form_class = AlbumVoteForm
    model = AlbumVote


    def form_valid(self, form):
        like = form.cleaned_data.get('like')
        user = self.request.user
        album_obj = Album.objects.get(pk=self.kwargs['song_id'])
        vote_obj, created = AlbumVote.objects.get_or_create(album = album_obj, user = user, like=like) 
        form.instance = vote_obj
        return super().form_valid(form)






class AlbumDetailView(DetailView):
    model = Album


class AlbumCreatView(CreateView):
    form_class = AlbumForm
    template_name = 'album/album_create.html'
    success_url = '/album/'


class AlbumDeleteView(DeleteView):
    model = Album
    success_url = reverse_lazy('music:album_list')


class AlbumUpdateView(UpdateView):
    model = Album
    form_class =AlbumForm #we can use form_class method or bellow fields method to declare the form
    # fields = ['title','discription','formate','singer']
    template_name_suffix = '_update_form'
    success_url = '/album/'

music/album/templates/album/album_confirm_delete.html
{% extends 'album/base.html' %}

{% block content %}
<div class="container">
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
</div>
{% endblock %}

music/album/templates/album/album_create.html
{% extends 'album/base.html' %}

{% block content %}
<div class="container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table table-bordered table-light">
                {{form.as_table}}
        </table>
        <button type="submit">Submit</button>
        
    </form>
</div>
{% endblock %}

music/album/templates/album/album_detail.html
{% extends 'album/base.html' %}

{% block content %}

<div class="container mt-5">
    {% if object %}

    <h4>Title of the album : {{object.title}}</h4>
    <h4>Description : {{object.discription}}</h4>
    <h4>Sung by : {{object.album_creator}}</h4>
    <h4 class="con-clock">Published on : {{ object.created}}</h4>  <!--|timesince we can use this after timestamp-->
    
    {% for song in object.songs %}

    <h4>{{song.song_title}}</h4>

    {% endfor %}

   

    <a href="{% url 'music:update_view' pk=object.id %}"><button>Update</button></a>
    <a href="{% url 'music:delete_view' pk=object.id %}"><button>Delete</button></a>


    {% else %}

    <h4>There is no information available on this album</h4>

    {% endif %}

    {% endblock %}

</div>

music/album/templates/album/album_list.html
{% extends 'album/base.html' %}

{% block content %}



  <div class="container">
    {% if object_list %}
        {% for album in object_list %}

        <div class="card my-3">
            <div class="card-header">
              Featured
            </div>
            <div class="card-body">
              <h5 class="card-title">
                
                    <a href="{% url 'music:detail_view' pk=album.id %}"><strong>{{album.title}}</strong></a>
                    {{album.vote}}
              </h5>
              <p class="card-text">{{album.discription}}.</p>
              <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
          </div><br>
        {% endfor %}
        {{page_obj.class_id}} @ {{timestamp}}
        component_name {{host}} {{timestamp}}
    {% else %}

    <h2>There are no albums available yet</h2>

    {% endif %}

    {% for vote in album.vote %}
          {{vote.song_title}}

    {% endfor %}



    <!-- <div class="loading" style="display: none;">
            Loading...
    </div>


    {% if page_obj.has_next %}
    <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}">More</a>
    {% endif %}


    {% block js %}

    <script>
        console.log('test')
        var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
            $('.loading').show();
            },
            onAfterPageLoad: function ($items) {
            $('.loading').hide();
            }
        });
    </script>
    {% endblock %} -->




<!-- PAGINATION -->

    {% if is_paginated %}
                 
      <div class="pagination">
          <span class="step-links">
              {% if page_obj.has_previous %}
                  <a href="?page=1">&laquo; first</a>
                  <a href="?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
      
              <span class="current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
      
              {% if page_obj.has_next %}
                  <a href="?page={{ page_obj.next_page_number }}">next</a>
                  <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
              {% endif %}
          </span>
      </div>
    {% endif %} 

  </div>

  
{% endblock %}

music/album/templates/album/album_update_form.html
{% extends 'album/base.html' %}

{% block content %}
<div class="container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table table-bordered table-light">
                {{form.as_table}}
        </table>
        <button type="submit">Update</button>
        
    </form>
</div>
{% endblock %}

music/album/templates/album/base.html
<!doctype html>
<html lang="en">
  <head>
      {% load staticfiles %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>

  </head>
  <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                  <a class="navbar-brand" href="#">Hidden brand</a>
                  <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Link</a>
                    <!-- </li>
                    <li class="nav-item">
                      <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li> -->

                    <li class="nav-item">
                      <a class="nav-link disabled " href="#" tabindex="-1" aria-disabled="true">{{request.user}}</a>
                    </li>
                  </ul>
                  {% if request.role == 'admin' %}
                  <a class="btn btn-success float-right mx-2" href="{%  url 'music:album_singer_create' %}">Add Album</a>
                  {% endif %}
                  <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  </form>
                </div>
              </nav>
    {% block content %}

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/infinite.min.js' %}"></script> -->
    {% block js %}{% endblock %}
  </body>
</html>

music/album/templates/album/multi_form_add.html
{% extends 'album/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-8">
            <form method="POST">
                {% csrf_token %}
                <table class="table table-bordered table-light">
                    {{singer_form|crispy}}
                    {{album_form|crispy}}
                    {{song_form}}
                    
                </table>
                <br>
                <button type="submit" class="btn btn-warning float-right mr-6">Update </button>
            </form>
        </div>
</div>
</div>

{% endblock %}

music/album/templates/album/multi_form_edit.html
{% extends 'album/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-8">
            <form method="POST">
                {% csrf_token %}
                <table class="table table-bordered table-light">
                    {{singer_form|crispy}}
                    {{album_form|crispy}}
                    {{error}}
                    

                    {% for form in song_form %}
                        {{form|crispy}}
                   
                    {% endfor %}
                    

                    
                    
                    
                </table>
                <br>
                <button type="submit" class="btn btn-warning float-right mr-6">Update </button>
            </form>
        </div>
</div>
</div>

{% endblock %}