music/music/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from user import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)

urlpatterns = [

    # path('', include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',include('album.urls')),
    # path('api/v1/', include('user.api_urls')),
    path('user/',include('user.urls')),
    path('accounts/',include('allauth.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/user/urls.py
from django.contrib import admin
from django.urls import path,include
# from .views import  RegisterView,
from django.contrib.auth import views as auth_view
from user import views as user_views
from django.conf import settings
from django.conf.urls.static import static




app_name = 'user'
urlpatterns = [
   
    
    # path('login/', auth_view.LoginView.as_view(),name='login'),
    path('login/', user_views.LoginFormView.as_view(),name='login'), 
    path('logout/',auth_view.LogoutView.as_view(),name='logout'),

    path('account/signup/', user_views.signup,name='sinup'),
    path('account/ajax/validate_username/', user_views.validate_username, name='validate_username'),
    path('account/account_activation_sent/', user_views.account_activation_sent, name='account_activation_sent'),
    path('account/activate/<uidb64>/<token>/', user_views.activate, name='activate'),
    path('account/signup_done/', user_views.signup_done, name='signup_done'),

    path('password_reset/',auth_view.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/',auth_view.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_view.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done',auth_view.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('profile/<int:pk>/',user_views.ProfileEditView.as_view(), name='edit_profile'),
    path('add_profile/<int:pk>/',user_views.ProfileAddView.as_view(), name='add_profile'),
    path('detail_profile/<int:pk>/',user_views.ProfileDetailView.as_view(), name='detail_profile'),

]







'''
need to install crispy form for better look using pip3 install django-crispy-forms,
and add the app in installed app like bellow

INSTALLED_APPS = [
    ...

    'crispy_forms',
]

and add the tag in settings.py as bellow

CRISPY_TEMPLATE_PACK = 'bootstrap4'

refer /home/sanjay/Hacker make/CRUD mixins/Bootstrap 4 Forms With Django for more info.
'''
    
    

music/user/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
from uuid import uuid4


User = get_user_model()


def get_profile_upload_to(instance,filename):
    new_filename = '{}.{}'.format(uuid4,filename.split('.')[-1])
    return "profile/{}/{}".format(instance.user.id, new_filename)


class ProfileImage(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_profile_upload_to)
    uploaded = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.user.username

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    bio = models.TextField(max_length=500,null=True, blank=True)
    location = models.CharField(max_length=50,null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    email_confirmed = models.BooleanField(default=False)



    def __str__(self):
        return self.user.username



@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

music/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import ProfileImage,Profile

User = get_user_model()

class SignUpForm(UserCreationForm):
    birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')
    


    class Meta:
        model = User
        fields = ['username','email', 'birth_date', 'password1', 'password2']


class ProfileImageForm(forms.ModelForm):
    

    class Meta:
        model = ProfileImage
        fields = ['image']


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['birth_date']

music/user/templates/user/views.py
from django.shortcuts import render,redirect

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login,authenticate
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth import get_user_model

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from user.tokens import account_activation_token
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_text


from .forms import SinupForm

User = get_user_model()



def signup(request):
    if request.method == 'POST':
        form = SinupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate Your MySite Account'
            message = render_to_string('user/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            return redirect('account_activation_sent')
    else:
        form = SinupForm()
    return render(request, 'user/register.html', {'form': form})



def account_activation_sent(request):
    return render(request, '')



def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('home')
    else:
        return render(request, 'user/account_activation_invalid.html')







# class RegisterView(CreateView):
#     template_name = 'user/register.html'
#     form_class = SinupForm
#     success_url = reverse_lazy('music:album_list')

    
    

music/user/views.py
from django.shortcuts import render,redirect,HttpResponse,get_object_or_404,HttpResponseRedirect
from django.core.exceptions import PermissionDenied

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login,authenticate
from django.contrib.auth import get_user_model
# from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views.generic import CreateView,UpdateView,DetailView,View

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from user.tokens import account_activation_token
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_text

from django.http import JsonResponse

from .forms import SignUpForm,ProfileImageForm,ProfileForm
from .models import ProfileImage,Profile


from .serializers import UserSerializer
from rest_framework import viewsets


User = get_user_model()



class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class ProfileEditView(View):
    profile_class = ProfileForm
    profile_image_class = ProfileImageForm
    template_name = 'user/profile_edit.html'

    def get(self,request,pk):
        if pk:
            user = User.objects.get(pk=pk)
            profile = Profile.objects.get(user = user)
            profile_image = ProfileImage.objects.get(user = user)
            profile_form = self.profile_class(instance = profile)
            profile_image_form = self.profile_image_class(instance = profile_image)
            
            context = {
            'profile_form':profile_form,
            'profile_image_form':profile_image_form
                }
            return render(request, self.template_name, context)

        else:
            profile_form = self.profile_class(None)
            profile_image_form = self.profile_image_class(None)
            context = {
                'profile_form':profile_form,
                'profile_image_form':profile_image_form
                }
            return render(request, self.template_name, context)


    def post(self,request,pk=None, **kwargs):

        user = User.objects.get(pk=pk)
        profile = Profile.objects.get(user = user)
        profile_image = ProfileImage.objects.get(user = user)
        profile_form = self.profile_class(request.POST,instance=profile)
        profile_image_form = self.profile_image_class(request.POST, request.FILES, instance=profile_image)

        if user == request.user:
            if profile_image_form.is_valid() and profile_form.is_valid():
                profile = profile_form.save(commit=False)
                profile_image = profile_image_form.save(commit=False)

                profile.user = self.request.user
                profile_image.user = self.request.user

                profile.save()
                profile_image.save()

                return redirect('music:album_list')

        context = {
                'profile_form':profile_form,
                'profile_image_form':profile_image_form,
                'error_message':"You could not able to edit other user's profile",
                }
        return render(request, self.template_name, context)
        



# class ProfileEditView(UpdateView):
#     model = ProfileImage
#     template_name = 'user/profile_edit.html'
#     form_class = ProfileImageForm
#     success_url = '/album/'

#     # We can use above form_class or below image_form to render form to user_profile template
#     def get_context_data(self,**kwargs):
#         ctx = super().get_context_data(**kwargs)
#         ctx['profile_form'] = self.profile_form
#         return ctx

#     def get_object(self,queryset=None):
#         profile = super().get_object(queryset)
#         user = self.request.user
#         if profile.user != user:
#             raise PermissionDenied('You can not edit other user profile')
#         return profile


#     def profile_form(self):
#         if self.request.user.is_authenticated:
#             return ProfileForm()
#         return None




class ProfileAddView(CreateView):
    model = ProfileImage
    form_class = ProfileImageForm
    template_name = 'user/user_profile.html'


    # def get_context_data(self,**kwargs):
    #     ctx = super().get_context_data(**kwargs)
    #     ctx['user'] = self.request.user
    #     return ctx

class ProfileDetailView(DetailView):
    model = User
    template_name = 'user/profile_detail.html'





def validate_username(request):
    username = request.GET.get('username',None)
    data = {
        'is_taken':User.objects.filter(username__iexact = username).exists()
    }

    if data['is_taken']:
        data['error_message'] = "A user with this username is already exists please change the username"
    return JsonResponse(data)


class LoginFormView(LoginView):

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['rend'] = 'This is for test'
        return ctx



# #We can use class based signup when we using allauth authentication

# class RegisterView(CreateView):
#     template_name = 'user/register.html'
#     form_class = SinupForm
#     success_url = reverse_lazy('music:album_list')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate Your MySite Account'
            test = render_to_string('user/test.html')
            print('test_1')
            message = render_to_string('user/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message,test)
            return redirect('user:account_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'user/register.html', {'form': form})



def account_activation_sent(request):
    return render(request, 'user/account_activation_sent.html')



def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('user:signup_done')
    else:
        return render(request, 'user/account_activation_invalid.html')



def signup_done(request):
    return render(request, 'user/signup_done.html')





    
    

music/user/templates/user/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}
{% endautoescape %}

music/user/templates/user/account_activation_invalid.html
<h1 style="color: red;" >SomeThing Went wrong with your credential. You Can't able to signup!</h1>

music/user/templates/user/account_activation_sent.html
<h3>Please confirm your email address to complete registration</h3>

music/user/templates/user/profile_detail.html
{% extends 'base.html' %}




{% block main %}
<div class="row">
    <div class="col md-6">
            <table class="table table-light table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>Username</th>
                        <td>{{object.username}}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>{{object.email}}</td>
                    </tr>
                    <tr>
                        <th>Birth date</th>
                        <td>{{object.profile.birth_date}}</td>
                    </tr>                                        
                </tbody>
            </table>
            <div class="text-right">
                <a class="btn btn-warning" href="{%  url 'user:edit_profile' pk=object.profileimage.id %}">Edit Profile</a>
            </div>
    </div>

    <div class="col md-6">
        <img src="{{object.profileimage.image.url}}">
    </div>
</div>

{% endblock %}

music/user/templates/user/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block main %}


<form method="post" enctype="multipart/form-data">{% csrf_token %}

    <p style="color: red;" >{{error_message}}</p>
    {{profile_form|crispy}}
    {{profile_image_form|crispy}}
    <button type="submit">Submit</button>
    
</form>

{% endblock %}

music/user/templates/user/register.html
{% extends 'base.html' %}

{% load socialaccount %}

{% providers_media_js %}

{% block main %}

{% load crispy_forms_tags %}

    <h2><strong> Register for cls-Pro</strong></h2>

    
        <form  method="post" data-validate-username-url="{% url 'user:validate_username' %}">
            {% csrf_token %}
<!-- {{form|crispy}} -->

            <div class="form-row">
                <div class="form-group col-md-6 mb-0">
                    {{form.username|as_crispy_field}}                   
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{form.email|as_crispy_field}}
                </div>
            </div>
            <div><label id="inval" style="color: red; font-size: smaller; visibility: hidden">Invalied {{data.error_message}} </label></div>

            <div class="form-row">
              <div class="form-group col-md-6 mb-0">
                  {{form.birth_date|as_crispy_field}}                   
              </div>
          </div>
            

            <div class="form-row">
                <div class="form-group col-md-6 mb-0">
                    {{form.password1|as_crispy_field}}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{form.password2|as_crispy_field}}
                </div>
            </div>
            
            <button class="btn btn-success" type="submit">Rgister</button>
            <a href="{% provider_login_url 'facebook' method='oauth2' %}">Facebook</a>
            <a href="{% provider_login_url 'google' %}">Google</a>
            
        </form>
    
{% endblock %}

{% block js %} 
<script>
    $("#id_username").change(function () {
        console.log( $(this).val() );
    });
</script> 

<script>
        $("#id_username").change(function () {
          var form = $(this).closest("form");
          $.ajax({
            url: form.attr("data-validate-username-url"),
            data: form.serialize(),
            dataType: 'json',
            success: function (data) {
              if (data.is_taken) {
                document.getElementById("inval").style.visibility="visible";
                document.getElementById("inval").innerHTML=data.error_message;
                // alert(data.error_message);
              }
              else{
                document.getElementById("inval").style.visibility="hidden";
              }
            }
          });
    
        });
      </script>

{% endblock %}

music/user/templates/user/signup_done.html
<h2>You have successfully signed up!</h2>

music/user/templates/user/test.html
This is testing