music/album/urls.py
from django.urls import path
from . import views
# from .views import  AlbumListView,AlbumDetailView,AlbumCreatView,AlbumDeleteView,AlbumUpdateView,AlbumSinger,SongDetailView




app_name = 'music'
urlpatterns = [
    path('album/',views.AlbumListView.as_view(), name='album_list' ),
    path('album/<int:pk>/', views.AlbumDetailView.as_view(), name='detail_view'),
    path('album/create/',views.AlbumCreatView.as_view(),name='create_view'),
    path('album/delete/<int:pk>/',views.AlbumDeleteView.as_view(),name='delete_view' ),
    path('album/update/<int:pk>/',views.AlbumUpdateView.as_view(),name='update_view'),
    path('album/multi/',views.AlbumSinger.as_view(),name='album_singer_create'),
    path('album/multi/<int:pk>/',views.AlbumSinger.as_view(),name='album_singer'),

    path('album/song/<int:pk>/',views.SongDetailView.as_view(), name='song_detail'),
    path('album/song/create/<int:song_id>/',views.SongVoteCreateView.as_view(), name='song_vote_create'),
    path('album/song/update/<int:song_id>/<int:pk>/', views.SongUpdateView.as_view(), name='song_vote_update')
    
]

music/music/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from user import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)

urlpatterns = [

    # path('', include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',include('album.urls')),
    # path('api/v1/', include('user.api_urls')),
    path('user/',include('user.urls')),
    path('accounts/',include('allauth.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/user/urls.py
from django.contrib import admin
from django.urls import path,include
# from .views import  RegisterView,
from django.contrib.auth import views as auth_view
from user import views as user_views
from django.conf import settings
from django.conf.urls.static import static




app_name = 'user'
urlpatterns = [
   
    
    # path('login/', auth_view.LoginView.as_view(),name='login'),
    path('login/', user_views.LoginFormView.as_view(),name='login'), 
    path('logout/',auth_view.LogoutView.as_view(),name='logout'),

    path('account/signup/', user_views.signup,name='sinup'),
    path('account/ajax/validate_username/', user_views.validate_username, name='validate_username'),
    path('account/account_activation_sent/', user_views.account_activation_sent, name='account_activation_sent'),
    path('account/activate/<uidb64>/<token>/', user_views.activate, name='activate'),
    path('account/signup_done/', user_views.signup_done, name='signup_done'),

    path('password_reset/',auth_view.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/',auth_view.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_view.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done',auth_view.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('profile/<int:pk>/',user_views.ProfileEditView.as_view(), name='edit_profile'),
    path('add_profile/<int:pk>/',user_views.ProfileAddView.as_view(), name='add_profile'),
    path('detail_profile/<int:pk>/',user_views.ProfileDetailView.as_view(), name='detail_profile'),

]







'''
need to install crispy form for better look using pip3 install django-crispy-forms,
and add the app in installed app like bellow

INSTALLED_APPS = [
    ...

    'crispy_forms',
]

and add the tag in settings.py as bellow

CRISPY_TEMPLATE_PACK = 'bootstrap4'

refer /home/sanjay/Hacker make/CRUD mixins/Bootstrap 4 Forms With Django for more info.
'''
    
    

music/templates/axes_lockout.html
<h1 style="color: red;" >Your account has been freezed</h1>

{{cooloff_time}} and {{failure_limit}}

music/templates/base.html
<!doctype html>
<html lang="en">
  <head>
      {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %}Cls-Pro{% endblock %}</title>

    <style>
        .mymdb-masthead{
            background-color: #EEEEEE;
            margin-bottom: 1em;
            
        }
    </style>

  </head>

  <body>

    <div class="mymdb-masthead">
        <div class="container">
            <nav class="nav">
                <div class="navbar-brand">Cls-Pro</div>
                <a class="nav-link" href="{% url 'music:album_list' %}">
                    Albums
                </a>
            </nav>

        </div>

    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                {% block main %}
                {% endblock %}
            </div>
            <div class="col-sm-3 offset-sm-1">
                {% block sidebar %}
                {% endblock %}
            </div>
        </div>
    </div>



    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script> -->
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/infinite.min.js' %}"></script>
    {% block js %} {% endblock %}
  </body>
</html>